/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.Homework4;

import com.opencsv.CSVReader;
import com.opencsv.CSVWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.List;

public class App {
 
    public static void main(String[] args) {
        String filepath = "src/Copy of MotorPH Employee Data.csv";
        try(CSVReader reader = new CSVReader(new FileReader(filepath))){
            reader.readNext();
            List<String[]> allUser = reader.readAll();
            for (String[] row : allUser){
                // row = {"Employee Number","last name", "first name"}
                System.out.println("Employee Number: " + row[0] +",Last Name:" +row[1] +",First Name:" +row[2]);
            }
        }catch(Exception e){
             }
    }
}


